spring:
    profiles:
        active: default
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/security_boot?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      #使用Druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接的等待时间
      maxWait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

      # 默认配置（stat,wall，log4j）
      filters: stat,wall,log4j
      # 配置StatFilter(手动配置)
      druid:
        filter:
          stat:
            db-type: mysql
            log-slow-sql: true
          # wallFilter
          wall:
            enabled: true
            db-type: mysql
            config:
              delete-allow: false
    themeleaf:
      cach: false
mybatis:
  config-location: classpath:config/mybatis-config.xml
